"""phase 4: epg_source and programme

Revision ID: 2cb512700ed6
Revises: ea95557655d6
Create Date: 2026-08-30 15:43:42.361300
"""

from __future__ import annotations

from collections.abc import Sequence

import app.db  # noqa: F401  custom column types (app.db.TZDateTime)
import sqlalchemy as sa
from alembic import op

revision: str = "2cb512700ed6"
down_revision: str | None = "ea95557655d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "epg_source",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("etag", sa.String(length=400), nullable=True),
        sa.Column("last_modified", sa.String(length=200), nullable=True),
        sa.Column("last_fetched_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column(
            "last_status",
            sa.Enum("pending", "ok", "error", name="epgstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("programme_count", sa.Integer(), nullable=False),
        sa.Column("refresh_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_epg_source_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_epg_source_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_epg_source")),
        sa.UniqueConstraint("tenant_id", "url", name="uq_epg_source_tenant_id_url"),
    )
    with op.batch_alter_table("epg_source", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_epg_source_source_id"), ["source_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_epg_source_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "programme",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("channel_id", sa.Uuid(), nullable=False),
        sa.Column("epg_source_id", sa.Uuid(), nullable=False),
        sa.Column("start_utc", app.db.TZDateTime(timezone=True), nullable=False),
        sa.Column("stop_utc", app.db.TZDateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("sub_title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("categories", sa.JSON(), nullable=False),
        sa.Column("episode_num", sa.String(length=64), nullable=True),
        sa.Column("year", sa.String(length=8), nullable=True),
        sa.Column("icon_url", sa.Text(), nullable=True),
        sa.Column("director", sa.Text(), nullable=True),
        sa.Column("is_movie", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
            name=op.f("fk_programme_channel_id_channel"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["epg_source_id"],
            ["epg_source.id"],
            name=op.f("fk_programme_epg_source_id_epg_source"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_programme_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programme")),
    )
    with op.batch_alter_table("programme", schema=None) as batch_op:
        batch_op.create_index(
            "ix_programme_channel_start", ["channel_id", "start_utc"], unique=False
        )
        batch_op.create_index("ix_programme_epg_source_id", ["epg_source_id"], unique=False)
        batch_op.create_index("ix_programme_tenant_start", ["tenant_id", "start_utc"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("programme", schema=None) as batch_op:
        batch_op.drop_index("ix_programme_tenant_start")
        batch_op.drop_index("ix_programme_epg_source_id")
        batch_op.drop_index("ix_programme_channel_start")

    op.drop_table("programme")
    with op.batch_alter_table("epg_source", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_epg_source_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_epg_source_source_id"))

    op.drop_table("epg_source")
    # ### end Alembic commands ###
