"""phase 7: connector

Revision ID: 87bc5ff5d591
Revises: cceff9302219
Create Date: 2026-08-30 17:15:26.338868
"""

from __future__ import annotations

from collections.abc import Sequence

import app.db  # noqa: F401  custom column types (app.db.TZDateTime)
import sqlalchemy as sa
from alembic import op


revision: str = "87bc5ff5d591"
down_revision: str | None = "cceff9302219"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("pairing_code", sa.String(length=16), nullable=True),
        sa.Column("pairing_expires_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("version", sa.String(length=40), nullable=True),
        sa.Column("last_seen_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("discovered", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_connector_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector")),
    )
    with op.batch_alter_table("connector", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_connector_pairing_code"), ["pairing_code"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_connector_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_connector_token_hash"), ["token_hash"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("connector", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_connector_token_hash"))
        batch_op.drop_index(batch_op.f("ix_connector_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_connector_pairing_code"))

    op.drop_table("connector")
    # ### end Alembic commands ###
