"""phase 6: tmdb_enrichment

Revision ID: cceff9302219
Revises: 2cb512700ed6
Create Date: 2026-08-30 16:59:05.848676
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db  # noqa: F401  custom column types (app.db.TZDateTime)


revision: str = "cceff9302219"
down_revision: str | None = "2cb512700ed6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tmdb_enrichment",
        sa.Column(
            "media_type",
            sa.Enum("movie", "tv", name="mediatype", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("query_key", sa.String(length=300), nullable=False),
        sa.Column("query_year", sa.String(length=8), nullable=False),
        sa.Column("negative", sa.Boolean(), nullable=False),
        sa.Column("fetched_at", app.db.TZDateTime(timezone=True), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("release_year", sa.String(length=8), nullable=True),
        sa.Column("overview", sa.Text(), nullable=True),
        sa.Column("tagline", sa.Text(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("runtime", sa.Integer(), nullable=True),
        sa.Column("director", sa.Text(), nullable=True),
        sa.Column("genres", sa.JSON(), nullable=False),
        sa.Column("cast", sa.JSON(), nullable=False),
        sa.Column("backdrop_url", sa.Text(), nullable=True),
        sa.Column("poster_url", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tmdb_enrichment")),
        sa.UniqueConstraint("media_type", "query_key", "query_year", name="uq_tmdb_enrichment_key"),
    )
    with op.batch_alter_table("tmdb_enrichment", schema=None) as batch_op:
        batch_op.create_index("ix_tmdb_enrichment_fetched", ["fetched_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tmdb_enrichment", schema=None) as batch_op:
        batch_op.drop_index("ix_tmdb_enrichment_fetched")

    op.drop_table("tmdb_enrichment")
    # ### end Alembic commands ###
