"""phase 3: source and channel

Revision ID: ea95557655d6
Revises: f3b66c8607c4
Create Date: 2026-08-30 15:16:50.148342
"""

from __future__ import annotations

from collections.abc import Sequence

import app.db  # noqa: F401  custom column types (app.db.TZDateTime)
import sqlalchemy as sa
from alembic import op

revision: str = "ea95557655d6"
down_revision: str | None = "f3b66c8607c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("m3u", "xtream", "stalker", name="sourcekind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("config_encrypted", sa.Text(), nullable=False),
        sa.Column("timezone_override", sa.String(length=64), nullable=True),
        sa.Column("clock_shift_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("refresh_interval_minutes", sa.Integer(), nullable=False),
        sa.Column("last_refreshed_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column(
            "last_status",
            sa.Enum("pending", "ok", "error", name="sourcestatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("channel_count", sa.Integer(), nullable=False),
        sa.Column("epg_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_source_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
    )
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "channel",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=400), nullable=False),
        sa.Column("ext_id", sa.String(length=256), nullable=True),
        sa.Column("name", sa.String(length=400), nullable=False),
        sa.Column("tvg_name", sa.String(length=400), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("group_title", sa.String(length=400), nullable=True),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("is_hd", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("stream_ref_encrypted", sa.Text(), nullable=False),
        sa.Column("clock_shift_seconds", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
            name=op.f("fk_channel_source_id_source"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_channel_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel")),
        sa.UniqueConstraint("source_id", "dedupe_key", name="uq_channel_source_id_dedupe_key"),
    )
    with op.batch_alter_table("channel", schema=None) as batch_op:
        batch_op.create_index("ix_channel_source_group", ["source_id", "group_title"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_source_id"), ["source_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_channel_source_id"))
        batch_op.drop_index("ix_channel_source_group")

    op.drop_table("channel")
    with op.batch_alter_table("source", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_tenant_id"))

    op.drop_table("source")
    # ### end Alembic commands ###
