"""phase 2 auth: tenant, user, credentials, sessions, tokens, audit

Revision ID: f3b66c8607c4
Revises:
Create Date: 2026-08-30 13:20:33.411499
"""

from __future__ import annotations

from collections.abc import Sequence

import app.db  # noqa: F401  (custom column types, e.g. app.db.TZDateTime)
import sqlalchemy as sa
from alembic import op

revision: str = "f3b66c8607c4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("default_timezone", sa.String(length=64), nullable=False),
        sa.Column("tmdb_token_encrypted", sa.String(length=1024), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenant")),
    )
    op.create_table(
        "user_account",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("email_verified_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_user_account_tenant_id_tenant"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
    )
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_account_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_account_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
            name=op.f("fk_audit_log_tenant_id_tenant"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_audit_log_user_id_user_account"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_event"), ["event"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_user_id"), ["user_id"], unique=False)

    op.create_table(
        "auth_session",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("rotated_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("expires_at", app.db.TZDateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["auth_session.id"],
            name=op.f("fk_auth_session_parent_id_auth_session"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_auth_session_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_session")),
    )
    with op.batch_alter_table("auth_session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_session_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_auth_session_user_id"), ["user_id"], unique=False)

    op.create_table(
        "email_token",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum("verify", "reset", name="emailtokenpurpose", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", app.db.TZDateTime(timezone=True), nullable=False),
        sa.Column("used_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_email_token_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_email_token")),
    )
    with op.batch_alter_table("email_token", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_email_token_token_hash"), ["token_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_email_token_user_id"), ["user_id"], unique=False)

    op.create_table(
        "password_credential",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("hash", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_password_credential_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_credential")),
        sa.UniqueConstraint("user_id", name=op.f("uq_password_credential_user_id")),
    )
    op.create_table(
        "totp_secret",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("secret_encrypted", sa.String(length=512), nullable=False),
        sa.Column("confirmed_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("recovery_codes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_totp_secret_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_totp_secret")),
        sa.UniqueConstraint("user_id", name=op.f("uq_totp_secret_user_id")),
    )
    op.create_table(
        "webauthn_challenge",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "registration",
                "authentication",
                name="webauthnchallengekind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("challenge", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", app.db.TZDateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_webauthn_challenge_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webauthn_challenge")),
    )
    with op.batch_alter_table("webauthn_challenge", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webauthn_challenge_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "webauthn_credential",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("transports", sa.String(length=120), nullable=True),
        sa.Column("aaguid", sa.String(length=64), nullable=True),
        sa.Column("nickname", sa.String(length=80), nullable=False),
        sa.Column("backed_up", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", app.db.TZDateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            app.db.TZDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_webauthn_credential_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webauthn_credential")),
        sa.UniqueConstraint("credential_id", name=op.f("uq_webauthn_credential_credential_id")),
    )
    with op.batch_alter_table("webauthn_credential", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webauthn_credential_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webauthn_credential", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webauthn_credential_user_id"))

    op.drop_table("webauthn_credential")
    with op.batch_alter_table("webauthn_challenge", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webauthn_challenge_user_id"))

    op.drop_table("webauthn_challenge")
    op.drop_table("totp_secret")
    op.drop_table("password_credential")
    with op.batch_alter_table("email_token", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_token_user_id"))
        batch_op.drop_index(batch_op.f("ix_email_token_token_hash"))

    op.drop_table("email_token")
    with op.batch_alter_table("auth_session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_session_user_id"))
        batch_op.drop_index(batch_op.f("ix_auth_session_token_hash"))

    op.drop_table("auth_session")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_user_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_event"))

    op.drop_table("audit_log")
    with op.batch_alter_table("user_account", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_account_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_user_account_email"))

    op.drop_table("user_account")
    op.drop_table("tenant")
    # ### end Alembic commands ###
